import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { Providers } from "./providers";
import { TopNavbar } from "./_components/nav-bar";
import { getServerAuthSession } from "~/server/auth";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logos/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Providers>
          {session && <TopNavbar />}
          {children}
        </Providers>
      </body>
    </html>
  );
}
